{
    "env" : {
        "browser" : true,
        "node" : true,
        "es6" : true
    },
    "rules" : {
        "no-unused-vars" : 2,
        "no-undef" : 2
    },
    "parserOptions": {
        "sourceType": "module"
    },
    "globals": {
      "browser" : true,
      "assert" : true,
      "expect" : true
    }
}